node_id = "dtn://node1/"
log_level = "Debug"

[Store]
path = "/tmp/dtn7_node1_store"

[Routing]
algorithm = "epidemic"

[Agents]
[Agents.REST]
address = "localhost:8081"

[Agents.UNIX]
socket = "/tmp/dtnd_node1.socket"

[[Listener]]
type = "mtcp"
address = ":4556"

[[Listener]]
type = "meshtastic"
address = "/tmp/mesh_node1.sock"
peer_id = "dtn://node2/"

[Cron]
dispatch = "10s"
gc = "1h15s"

[[Peer]]
address = "mtcp://127.0.0.1:4557"
node_id = "dtn://node2/"
